name: MSVC(Win32)+GCC(Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan prepare
      run: conan profile detect --force && echo "${{ steps.conan.outputs.version }}"

    - name: Conan install
      run: conan install . --build=missing -vvv --settings compiler.cppstd=20

    - name: Build
      run: conan build -vvv --build=missing --settings compiler.cppstd=20 .
      
